### ISSUE TITLE
Question/ Enhancement: Does the image support ARM architectures?

### ISSUE THREAD

**Issue by SeppPenner** [timescale/timescaledb-docker#25] opened 2018-09-05 08:50 UTC
The original Postgres image supports ARM architectures: https://hub.docker.com/_/postgres/

> Supported architectures: (more info)
> amd64, arm32v5, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x

Does the TimescaleDB docker image provide this feature, too? I wanted to run it on a Raspberry Pi and got the error:` standard_init_linux.go:190: exec user process caused "exec format error"`

If it is not available for ARM architectures, this issue should be considered as an enhancement.

**Comment by RobAtticus** [comment] 2018-09-20 15:13
Thanks for the suggestion. I am not 100% sure what it would take to get running on ARM personally. Maybe it is a matter of using a different image than alpine, but I'm wondering from the error if the issue is actually 32-bit vs 64-bit?

**Comment by cljk** [comment] 2018-10-09 21:19
Wanted to try the same... to store time series data from several measuring points on rpie. Good to know that's not working currently - then I can stick to plain postgres for now and perhaps switch later...

**Comment by adwk67** [comment] 2019-02-25 10:19
Just in case this helps somebody: I'm able to get timescale-DB running on ARMv7 (32-Bit) by changing the `tools ` image to this:

`FROM balenalib/armv7hf-alpine-golang as tools`

**Caveats**

- I had to build on arm hardware and then push to my docker repository (I then redeployed from the repository to check everything works)
- I removed all the stuff relating to the "old" versions due to space requirements

I can also build this image on my windows laptop using the `RUN [ "cross-build-start" ]` and `RUN [ "cross-build-end" ]` directives either side of the tools-build, but the deploy to ARM does not work: I'm no docker guru but it seems as though the `postgres:9.6-alpine` image pulls in dependencies based on the build environment and so building on non-ARM and then deploying to ARM does not work.

**Comment by tkurki** [comment] 2019-02-25 12:52
@adwk67 have you tried using arm32v7/postgres as the base Postgres image?

**Comment by adwk67** [comment] 2019-02-25 12:56
> @adwk67 have you tried using arm32v7/postgres as the base Postgres image?

@tkurki yes, but it didn't work (I got the `exec format` error).

**Comment by tkurki** [comment] 2019-02-25 18:01
I was able to build a working (tested on my RPi) ARM image on my Mac with https://github.com/tkurki/timescaledb-docker/commit/613d03a9009019c52c53d04b0a4eec70c1f3d510. 

I picked arm32v6/postgres because https://hub.docker.com/r/arm32v7/postgres/ has no alpine images.

If anybody wants to give it a spin I pushed it to https://hub.docker.com/r/tkurki/timescale-test.

Next steps:
- build on amd64 with qemu?
- switch to arm32v7/postgres?
- (same for postgis)

**Comment by oldgreen** [comment] 2019-04-17 12:20
I was able to build the image on AArch64 (Debian arm64) with the following patch (inspired by https://github.com/golang/go/issues/26307):

```
diff --git a/Dockerfile b/Dockerfile
index 62f5e3f..eb3e6be 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4,7 +4,7 @@ ARG PG_VERSION
 ############################
 FROM golang:alpine AS tools
 
-ENV TOOLS_VERSION 0.4.1
+ENV TOOLS_VERSION=0.4.1 CGO_ENABLED=0
 
 RUN apk update && apk add --no-cache git \
     && mkdir -p ${GOPATH}/src/github.com/timescale/ \
```

Without the patch the image build failed:
```
[...]
Step 3/33 : ENV TOOLS_VERSION 0.4.1
 ---> Running in a7073f216009
Removing intermediate container a7073f216009
 ---> 15b0161bb773
Step 4/33 : RUN apk update && apk add --no-cache git     && mkdir -p ${GOPATH}/src/github.com/timescale/     && cd ${GOPATH}/src/github.com/timescale/     && git clone https://github.com/timescale/timescaledb-tune.git     && git clone https://github.com/timescale/timescaledb-parallel-copy.git     && cd timescaledb-tune/cmd/timescaledb-tune     && git fetch && git checkout --quiet $(git describe --abbrev=0)     && go get -d -v     && go build -o /go/bin/timescaledb-tune     && cd ${GOPATH}/src/github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy     && git fetch && git checkout --quiet $(git describe --abbrev=0)     && go get -d -v     && go build -o /go/bin/timescaledb-parallel-copy
 ---> Running in 2ef27b8bbf35
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/aarch64/APKINDEX.tar.gz
v3.9.3-23-g4281a184d7 [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.3-15-g583c0d55e9 [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
OK: 9541 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/aarch64/APKINDEX.tar.gz
(1/6) Installing nghttp2-libs (1.35.1-r0)
(2/6) Installing libssh2 (1.8.2-r0)
(3/6) Installing libcurl (7.64.0-r1)
(4/6) Installing expat (2.2.6-r0)
(5/6) Installing pcre2 (10.32-r1)
(6/6) Installing git (2.20.1-r0)
Executing busybox-1.29.3-r10.trigger
OK: 20 MiB in 21 packages
Cloning into 'timescaledb-tune'...
Cloning into 'timescaledb-parallel-copy'...
github.com/fatih/color (download)
github.com/pbnjay/memory (download)
github.com/jmoiron/sqlx (download)
github.com/lib/pq (download)
# github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy
/usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exec: "gcc": executable file not found in $PATH

The command '/bin/sh -c apk update && apk add --no-cache git     && mkdir -p ${GOPATH}/src/github.com/timescale/     && cd ${GOPATH}/src/github.com/timescale/     && git clone https://github.com/timescale/timescaledb-tune.git     && git clone https://github.com/timescale/timescaledb-parallel-copy.git     && cd timescaledb-tune/cmd/timescaledb-tune     && git fetch && git checkout --quiet $(git describe --abbrev=0)     && go get -d -v     && go build -o /go/bin/timescaledb-tune     && cd ${GOPATH}/src/github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy     && git fetch && git checkout --quiet $(git describe --abbrev=0)     && go get -d -v     && go build -o /go/bin/timescaledb-parallel-copy' returned a non-zero code: 2
Makefile:15: recipe for target '.build_1.2.2_pg10' failed
make: *** [.build_1.2.2_pg10] Error 2
```

**Comment by jeteon** [comment] 2019-06-12 21:11
Thank you all for documenting your workarounds for this issue. It has really been helpful. 

I just wanted to add that https://hub.docker.com/r/arm32v7/postgres/ has Alpine images now. I was successfully able to build an image by replacing the golang and postgres image references with the `arm32v7/*` ones.

**Comment by NFDWADM** [comment] 2020-03-03 09:23
> Thank you all for documenting your workarounds for this issue. It has really been helpful.
> 
> I just wanted to add that https://hub.docker.com/r/arm32v7/postgres/ has Alpine images now. I was successfully able to build an image by replacing the golang and postgres image references with the `arm32v7/*` ones.

Could you link your script? Because I did that too and my build fails because of the old timescaledb-image that is pulled during build.

**Comment by dekiesel** [comment] 2020-03-03 09:27
> Thank you all for documenting your workarounds for this issue. It has really been helpful.
> 
> I just wanted to add that https://hub.docker.com/r/arm32v7/postgres/ has Alpine images now. I was successfully able to build an image by replacing the golang and postgres image references with the `arm32v7/*` ones.

Could you link your script? Because I did that too and my build fails because of the old timescaledb-image that is pulled during build.

**Comment by yangm97** [comment] 2020-03-17 15:40
@dekiesel I use the `multiarch/qemu-user-static` image to enable arm32 binary execution on amd64 hosts plus the following dockerfile:

```
############################
# Build tools binaries in separate image
############################
FROM arm32v7/golang:1.13.7-alpine@sha256:07e0051866aa6cd44765d37af613a9efac3666956a5da3d092735ee9d4956514 AS tools

ENV TOOLS_VERSION 0.7.0

RUN apk update && apk add --no-cache git \
    && mkdir -p ${GOPATH}/src/github.com/timescale/ \
    && cd ${GOPATH}/src/github.com/timescale/ \
    && git clone https://github.com/timescale/timescaledb-tune.git \
    && git clone https://github.com/timescale/timescaledb-parallel-copy.git \
    # Build timescaledb-tune
    && cd timescaledb-tune/cmd/timescaledb-tune \
    && git fetch && git checkout --quiet $(git describe --abbrev=0) \
    && go get -d -v \
    && go build -o /go/bin/timescaledb-tune \
    # Build timescaledb-parallel-copy
    && cd ${GOPATH}/src/github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy \
    && git fetch && git checkout --quiet $(git describe --abbrev=0) \
    && go get -d -v \
    && go build -o /go/bin/timescaledb-parallel-copy

############################
# Now build image and copy in tools
############################

FROM arm32v7/postgres:11.6-alpine@sha256:c4baced0792c50f01d6feadb78bd8b12971ad8886e30d73f467a6b747b933494
ARG OSS_ONLY

# Update list above to include previous versions when changing this
ENV TIMESCALEDB_VERSION 1.4.0

COPY --from=tools /go/bin/* /usr/local/bin/

RUN set -ex \
    && apk add --no-cache --virtual .fetch-deps \
                ca-certificates \
                git \
                openssl \
                openssl-dev \
                tar \
    && mkdir -p /build/ \
    && git clone https://github.com/timescale/timescaledb /build/timescaledb \
    \
    && apk add --no-cache --virtual .build-deps \
                coreutils \
                dpkg-dev dpkg \
                gcc \
                libc-dev \
                make \
                cmake \
                util-linux-dev \
    \
    # Build current version \
    && cd /build/timescaledb && rm -fr build \
    && git checkout ${TIMESCALEDB_VERSION} \
    && ./bootstrap -DPROJECT_INSTALL_METHOD="docker"${OSS_ONLY} \
    && cd build && make install \
    && cd ~ \
    \
    && apk del .fetch-deps .build-deps \
    && rm -rf /build \
    && sed -r -i "s/[#]*\s*(shared_preload_libraries)\s*=\s*'(.*)'/\1 = 'timescaledb,\2'/;s/,'/'/" /usr/local/share/postgresql/postgresql.conf.sample
```

@RobAtticus what needs to be done to get arm32 support upstreamed? Do we need to use docker multi arch manifests or do you think it's enough to push arm32 images as alternate tags? multi arch manifests are more friendly to the final user but alternate tags would be easier to add into the Makefile.

**Comment by huonw** [comment] 2020-12-21 23:15
The new Apple M1 processors are ARM (ARM64/aarch64 specifically), seem to be pretty popular among devs and Docker for Mac [will soon be running ARM64 images natively](https://docs.docker.com/docker-for-mac/apple-m1/). Given that, this and/or #97 are likely to be more desirable, and so it'd be great to see ARMv7 and ARM64 images published officially in some form.

(A multi-arch manifest likely means many downstream Dockerfiles with `FROM timescale/timescaledb` or `FROM timescale/timescaledb-postgis` can be built for new platforms with no changes.)

**Comment by k-rus** [comment] 2020-12-22 08:18
[Latest docker images](https://hub.docker.com/r/timescale/timescaledb/tags?page=1&ordering=last_updated) include ARM v6 and v7 and ARM 64. Does it satisfy the request?

**Comment by huonw** [comment] 2020-12-23 04:03
That's great!

However, it looks like [the `timescaledb-postgis` images are still only amd64](https://hub.docker.com/r/timescale/timescaledb-postgis/tags?page=1&ordering=last_updated). Unfortunately, it looks like it may not be as simple as just building the Dockerfile for all those platforms, as it doesn't seem to work directly (on ARMv7):

```bash
.../timescaledb-docker/postgis $ make
docker build --build-arg POSTGIS_VERSION=2.5.5 --build-arg PG_VERSION_TAG=pg12 -t timescaledev/timescaledb-postgis:2.0.0-pg12 -t timescaledev/timescaledb-postgis:latest-pg12 .

[...] 

+ apk add --no-cache --virtual .build-deps autoconf automake file json-c-dev libtool libxml2-dev make perl llvm clang clang-dev g++ gdal-dev geos-dev proj-dev protobuf-c-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armv7/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  gdal-dev (missing):
    required by: .build-deps-20201223.022706[gdal-dev]

[...]
```

It looks like the `gdal` & `gdal-dev` packages are only available for `ppc64le`, `x86_64`, and `aarch64` architectures in [the Alpine 3.12 branch](https://pkgs.alpinelinux.org/packages?name=gdal&branch=v3.12), while [the edge branch](https://pkgs.alpinelinux.org/packages?name=gdal&branch=edge) additionally includes `x86`, `armhf`, and `armv7` architectures. I had a minute or two to quickly try two naive tricks to use the `edge` repositories:

- adding the `edge` repositories for all `apk` operations, which to understandably just leave the image in an inconsistent/broken state where `wget` doesn't work: `wget: bad address 'github.com'`.

  <details><summary>Click for diff and more output</summary>

  ```diff
  diff --git a/postgis/Dockerfile b/postgis/Dockerfile
  index a38cfb3..277ad29 100644
  --- a/postgis/Dockerfile
  +++ b/postgis/Dockerfile
  @@ -8,2 +8,3 @@ ENV POSTGIS_VERSION ${POSTGIS_VERSION:-2.5.3}
   RUN set -ex \
  +    && echo -e "http://dl-cdn.alpinelinux.org/alpine/edge/main\nhttp://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
       && apk add --no-cache --virtual .fetch-deps \
  ```

  ```shell
  .../timescaledb-docker/postgis $ make
  docker build --build-arg POSTGIS_VERSION=2.5.5 --build-arg PG_VERSION_TAG=pg12 -t timescaledev/timescaledb-postgis:2.0.0-pg12 -t timescaledev/timescaledb-postgis:latest-pg12 .

  [...]

  + cd /tmp
  + wget https://github.com/postgis/postgis/archive/2.5.5.tar.gz -O -
  + tar -xz
  wget: bad address 'github.com'
  gzip: invalid magic
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now

  [...]
  ```

   </details>

- installing just `gdal`/`gdal-dev` from the `edge` repositories, which seems to confuse the build system about PROJ in particular: `configure: error: could not find libproj`.

  <details><summary>Click for diff and more output</summary>

  ```diff
  diff --git a/postgis/Dockerfile b/postgis/Dockerfile
  index a38cfb3..3d78a83 100644
  --- a/postgis/Dockerfile
  +++ b/postgis/Dockerfile
  @@ -32,3 +32,2 @@ RUN set -ex \
           g++ \
  -        gdal-dev \
           geos-dev \
  @@ -36,2 +35,3 @@ RUN set -ex \
           protobuf-c-dev \
  +    && apk add --no-cache --virtual .build-deps2 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community gdal-dev \
       && cd /tmp \
  @@ -49,3 +49,2 @@ RUN set -ex \
           geos \
  -        gdal \
           proj \
  @@ -53,4 +52,5 @@ RUN set -ex \
           libstdc++ \
  +    && apk add --no-cache --virtual .postgis-rundeps2 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community gdal \
       && cd / \
       && rm -rf /tmp/postgis-${POSTGIS_VERSION} \
  -    && apk del .fetch-deps .build-deps
  +    && apk del .fetch-deps .build-deps .build-deps2
  ```

  ```shell
  .../timescaledb-docker/postgis $ make
  docker build --build-arg POSTGIS_VERSION=2.5.5 --build-arg PG_VERSION_TAG=pg12 -t timescaledev/timescaledb-postgis:2.0.0-pg12 -t timescaledev/timescaledb-postgis:latest-pg12 .

  [...]

  + ./configure
  [...]
  checking for geos-config... /usr/bin/geos-config
  checking GEOS version... 3.8.1
  checking geos_c.h usability... yes
  checking geos_c.h presence... yes
  checking for geos_c.h... yes
  checking for initGEOS in -lgeos_c... yes
  checking for sfcgal-config... no
  [...]
  checking for shared library run path origin... /bin/sh: can't open 'build-aux/config.rpath': No such file or directory
  done
  checking for CFPreferencesCopyAppValue... no
  checking for CFLocaleCopyCurrent... no
  checking for GNU gettext in libc... no
  checking for iconv... yes
  checking for working iconv... yes
  checking for GNU gettext in libintl... no
  checking whether to use NLS... no
  checking for proj_api.h... yes
  checking for pj_get_release in -lproj... no
  configure: error: could not find libproj - you may need to specify the directory of a PROJ.4 installation using --with-projdir

  [...]
  ```

  </details>

**Comment by dekiesel** [comment] 2020-12-23 09:58
In case it's interesting for anybody: I have a working dockerfile for timescaledb-postgis on armv7 here: https://github.com/dekiesel/arm7v32_timescaledb

Sorry for bad formatting, I am on mobile.

**Comment by k-rus** [comment] 2020-12-29 07:56
@huonw Sorry for the late reply. I confirm that [timescaledb-postgis](https://hub.docker.com/r/timescale/timescaledb-postgis/tags?page=1&ordering=last_updated) is only for single architecture AMD64. Can you open a new issue, since this one is dedicated to timescaledb itself and was resolved?

**Comment by huonw** [comment] 2020-12-29 09:32
No worries! It looks like #97 covers the `timescaledb-postgis` image specifically.

**Comment by k-rus** [comment] 2020-12-29 09:35
@huonw Thank you for finding the already exist issue!

I am closing this issue as it is resolved.

**Closed by k-rus** 2020-12-29 09:35 UTC

**Comment by SeppPenner** [comment] 2021-01-03 15:15
Nice work, I didn't see the updates before. Yes, this works for me :)

**Comment by mdczaplicki** [comment] 2022-11-22 19:51
What about this image: https://hub.docker.com/r/timescale/timescaledb-ha , can it be build for arm64v8?
