### ISSUE TITLE
Signal 11: Segmentation fault when starting on Raspberry Pi 4

### ISSUE THREAD

**Issue by wijnsema** [timescale/timescaledb-docker#136] opened 2021-02-16 15:27 UTC
When I run 

`docker run -d --name timescaledba1 -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:2.0.1-pg11`

on a Raspberry Pi 4 timescaledb/postgresql fails to start with the above mentioned Segmentation fault. It will restart a few seconds later only to fail again with the same error.

Just some time ago I was able to run timescaledb within the Iotstack [IOTstack](https://github.com/SensorsIot/IOTstack) but it stopped working and I can't figure out why. 

This is the result from docker logs: pi@iotstack:~/iotstack $ docker logs timescaledba1

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... GMT
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
sh: locale: not found
1970-05-03 10:46:56.010 GMT [31] WARNING:  no usable system locales were found
performing post-bootstrap initialization ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....1970-05-01 22:22:24.010 GMT [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
.1970-05-01 22:22:24.010 GMT [36] LOG:  startup process (PID 37) was terminated by signal 11: Segmentation fault
1970-05-01 22:22:24.010 GMT [36] LOG:  aborting startup due to startup process failure
1970-05-01 22:22:24.010 GMT [36] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
```

I also tried postgresql version 11 and 10, and timescale 1.7, same result.

- Context: Raspberry Pi 4, 2 GB, booted from Samsung T7 SSD
- Docker: Server: Docker Engine - Community   Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:57 2021
  OS/Arch:          linux/arm

**Comment by svenklemm** [comment] 2021-02-22 22:49
This is caused by a change in the alpine base image you need to upgrade your docker. See https://github.com/timescale/timescaledb/issues/2968 for more information.

Closing this. Feel free to reopen if you still experience the issue after upgrading docker.

**Closed by svenklemm** 2021-02-22 22:49 UTC

**Comment by ARMATAV** [comment] 2021-02-24 23:28
@svenklemm Hey, running into this issue on the Pi - can you clarify what you mean by upgrading Docker? `20.10.3` is the latest release at the moment.

**Comment by wijnsema** [comment] 2021-02-25 00:15
@ARMATAV I think it has to do with `libsecomp2` package being 2.3.3. But on my Pi 4 this package seems to be up to date, so the fix in 2.4.4 is not available, at least not with the package manager. No idea what I should do next, @svenklemm any idea?

**Comment by ARMATAV** [comment] 2021-02-25 01:37
@wijnsema Downgrading to 2.0.0 worked as a stop-gap for me, try it out - it should help. They mentioned somewhere in the other threads the issue arose in 2.0.1

**Comment by svenklemm** [comment] 2021-04-03 12:54
You can find additional information about the version requirements here: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
